version: '3.8'
services:
  mongodb-chat:
    image: mongo:latest
    container_name: mongodb-chat
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=0000
  mongo-express-chat:
    image: mongo-express:latest
    container_name: mongo-express-chat
    restart: always
    ports:
      - '8083:8081'
    environment:
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=0000
      - ME_CONFIG_MONGODB_SERVER=mongodb-chat
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb-chat
volumes:
  data: {}

networks:
  chat_network:
    external: true
