services:
  chat:
    build:
      context: ../../chat-app
      dockerfile: Dockerfile
    container_name: chat-server
    restart: always
    ports:
      - '10030:10030'
    env_file:
      - ../../chat-app/.env.production
    environment:
      MYSQL_HOST: mysql-chat
      MYSQL_PORT: 3306
      MONGO_HOST: mongodb-chat
      MONGO_PORT: 27017
    networks:
      - chat_network

networks:
  chat_network:
    external: true
